//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roxority_BuildZen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("roxority_BuildZen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; (Copyright &amp;copy; 2008-2011 &lt;a href=&quot;http://roxority.com&quot; target=&quot;_blank&quot;&gt;ROXORITY.com&lt;/a&gt; Ltd. All rights reserved.).
        /// </summary>
        internal static string HeadLine {
            get {
                return ResourceManager.GetString("HeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; (Copyright &amp;copy; 2008-2011 &lt;a href=&quot;http://roxority.com&quot; target=&quot;_blank&quot;&gt;ROXORITY.com&lt;/a&gt; Ltd. Alle Rechte vorbehalten.).
        /// </summary>
        internal static string HeadLine_de {
            get {
                return ResourceManager.GetString("HeadLine_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;{$HELP_TITLE$}&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;_html/help.tlhr.css&quot;/&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body, table, tr, td {
        ///				font-family: &quot;Lucida Grande&quot;, &quot;Trebuchet MS&quot;, Sans-Serif;
        ///				font-size: 12px;
        ///				background-color: #f0f0f0;
        ///				color: #303030;
        ///			}
        ///			a, a:visited, a:active, a:link, a:hover {
        ///				text-decoration: underline;
        ///				color: #cd3700;
        ///				font-weight: bold;
        ///			}
        ///			a:hover {
        ///				background-color: #cd3700;
        ///				color: #f0f0f0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlIndexFile {
            get {
                return ResourceManager.GetString("HtmlIndexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;{$HELP_TITLE$}&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;help.tlhr.css&quot;/&gt;
        ///		&lt;script type=&quot;text/javascript&quot; language=&quot;JavaScript&quot; src=&quot;jQuery.js&quot;&gt;&lt;/script&gt;
        ///		&lt;script type=&quot;text/javascript&quot; language=&quot;JavaScript&quot; src=&quot;help/res/top_up/top_up-min.js&quot;&gt;&lt;/script&gt;
        ///		&lt;script type=&quot;text/javascript&quot; language=&quot;JavaScript&quot;&gt;
        ///			TopUp.images_path = &apos;help/res/top_up/&apos;;
        ///			jQuery(document).ready(function() {
        ///				jQuery(&apos;img.rox-docpic&apos;).wrap(function() { return &apos;&lt;a class=&quot;top_up&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlTemplateFile {
            get {
                return ResourceManager.GetString("HtmlTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;HTML&gt;
        ///&lt;HEAD&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft&amp;reg; HTML Help Workshop 4.1&quot;&gt;
        ///&lt;!-- Sitemap 1.0 --&gt;
        ///&lt;/HEAD&gt;&lt;BODY&gt;
        ///&lt;UL&gt;
        ///&lt;/UL&gt;
        ///&lt;/BODY&gt;&lt;/HTML&gt;
        ///.
        /// </summary>
        internal static string IndexFile {
            get {
                return ResourceManager.GetString("IndexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x409 English (United States).
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x407 German (Germany).
        /// </summary>
        internal static string Lang_de {
            get {
                return ResourceManager.GetString("Lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Help.
        /// </summary>
        internal static string NameSuffix {
            get {
                return ResourceManager.GetString("NameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Hilfe.
        /// </summary>
        internal static string NameSuffix_de {
            get {
                return ResourceManager.GetString("NameSuffix_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OPTIONS]
        ///Binary Index=No
        ///Compatibility=1.0
        ///Compiled file=..\..\WspBuilder\zup\docs\{$OUTNAME$}.chm
        ///Contents file={$NAME$}.hhc
        ///Default topic={$TOPIC$}.html
        ///Display compile progress=No
        ///Full-text search=Yes
        ///Index file={$NAME$}.hhk
        ///Language={$LANG$}
        ///Title={$TITLE$}
        ///
        ///
        ///[FILES]
        ///{$FILES$}
        ///[INFOTYPES]
        ///
        ///.
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  Product Documentation.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-Produktdokumentation.
        /// </summary>
        internal static string Title_de {
            get {
                return ResourceManager.GetString("Title_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML//EN&quot;&gt;
        ///&lt;HTML&gt;
        ///&lt;HEAD&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content=&quot;Microsoft&amp;reg; HTML Help Workshop 4.1&quot;&gt;
        ///&lt;!-- Sitemap 1.0 --&gt;
        ///&lt;/HEAD&gt;&lt;BODY&gt;
        ///&lt;OBJECT type=&quot;text/site properties&quot;&gt;
        ///	&lt;param name=&quot;Window Styles&quot; value=&quot;0x801220&quot;&gt;
        ///&lt;/OBJECT&gt;
        ///&lt;UL&gt;
        ///{$TOC$}
        ///&lt;/UL&gt;
        ///&lt;/BODY&gt;&lt;/HTML&gt;
        ///.
        /// </summary>
        internal static string TocFile {
            get {
                return ResourceManager.GetString("TocFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;LI&gt; &lt;OBJECT type=&quot;text/sitemap&quot;&gt;
        ///		&lt;param name=&quot;Name&quot; value=&quot;{1}&quot;&gt;
        ///		&lt;param name=&quot;Local&quot; value=&quot;{0}.html&quot;&gt;
        ///		&lt;/OBJECT&gt;
        ///.
        /// </summary>
        internal static string TocItem {
            get {
                return ResourceManager.GetString("TocItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message? Open docs\{0}-Help.html instead..
        /// </summary>
        internal static string TocTitle {
            get {
                return ResourceManager.GetString("TocTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlermeldung? Oeffnen Sie docs\{0}-Hilfe.html stattdessen..
        /// </summary>
        internal static string TocTitle_de {
            get {
                return ResourceManager.GetString("TocTitle_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; (Copyright &amp;copy; 2008-2011 &lt;a target=&quot;_blank&quot; href=&quot;http://yukkalab.com&quot;&gt;Yukka GmbH&lt;/a&gt; &amp;amp; &lt;a href=&quot;http://roxority.com&quot; target=&quot;_blank&quot;&gt;ROXORITY Ltd.&lt;/a&gt; All rights reserved.).
        /// </summary>
        internal static string WhiteHeadLine {
            get {
                return ResourceManager.GetString("WhiteHeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; (Copyright &amp;copy; 2008-2011 &lt;a target=&quot;_blank&quot; href=&quot;http://yukkalab.com&quot;&gt;Yukka GmbH&lt;/a&gt; &amp;amp; &lt;a href=&quot;http://roxority.com&quot; target=&quot;_blank&quot;&gt;ROXORITY Ltd.&lt;/a&gt; Alle Rechte vorbehalten.).
        /// </summary>
        internal static string WhiteHeadLine_de {
            get {
                return ResourceManager.GetString("WhiteHeadLine_de", resourceCulture);
            }
        }
    }
}
