//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roxority_LookupZen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("roxority_LookupZen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _AdminHelpTopics {
            get {
                return ResourceManager.GetString("_AdminHelpTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; 2009 ROXORITY Ltd. All rights reserved..
        /// </summary>
        internal static string _Copyright {
            get {
                return ResourceManager.GetString("_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupZen.
        /// </summary>
        internal static string _Editions {
            get {
                return ResourceManager.GetString("_Editions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intro,setup,farm_site_config,release_notes,eula.
        /// </summary>
        internal static string _HelpTopics {
            get {
                return ResourceManager.GetString("_HelpTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/images/roxority_LookupZen/ewr052.gif.
        /// </summary>
        internal static string _LogoImageUrl {
            get {
                return ResourceManager.GetString("_LogoImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefLink.
        /// </summary>
        internal static string _MappingKey {
            get {
                return ResourceManager.GetString("_MappingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 237, 85, 209, 49, 73, 6, 147, 117, 81, 68, 162, 15, 109, 26, 59, 67, 58, 197, 52, 244, 164, 186, 179, 155, 234, 21, 245, 9, 209, 109, 131, 225, 17, 75, 196, 68, 68, 131, 184, 74, 240, 105, 246, 241, 193, 64, 17, 214, 143, 28, 43, 219, 101, 9, 167, 182, 248, 18, 61, 212, 94, 98, 178, 60, 72, 240, 218, 212, 177, 48, 134, 151, 116, 119, 23, 57, 165, 35, 243, 188, 76, 32, 252, 71, 223, 111, 231, 205, 18, 12, 59, 219, 32, 48, 1, 212, 212, 235, 173 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _ProductID {
            get {
                return ResourceManager.GetString("_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roxority_ExportZen.
        /// </summary>
        internal static string _ProductName {
            get {
                return ResourceManager.GetString("_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupZen.
        /// </summary>
        internal static string _ProductTitle {
            get {
                return ResourceManager.GetString("_ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _Settings {
            get {
                return ResourceManager.GetString("_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string _Version {
            get {
                return ResourceManager.GetString("_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roxority_.
        /// </summary>
        internal static string _WhiteLabel {
            get {
                return ResourceManager.GetString("_WhiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Br&amp;uuml;sseler Stra&amp;szlig;e 14&lt;br /&gt;13353 Berlin, Germany.
        /// </summary>
        internal static string _WhiteLabelAddress {
            get {
                return ResourceManager.GetString("_WhiteLabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupZen-Support@roxority.com.
        /// </summary>
        internal static string _WhiteLabelEmail {
            get {
                return ResourceManager.GetString("_WhiteLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROXORITY Ltd..
        /// </summary>
        internal static string _WhiteLabelTitle {
            get {
                return ResourceManager.GetString("_WhiteLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://roxority.com/.
        /// </summary>
        internal static string _WhiteLabelUrl {
            get {
                return ResourceManager.GetString("_WhiteLabelUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact-about/#down.
        /// </summary>
        internal static string _WhiteLabelUrlContact {
            get {
                return ResourceManager.GetString("_WhiteLabelUrlContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldType:roxority_LookupZenField.
        /// </summary>
        internal static string _WssItems {
            get {
                return ResourceManager.GetString("_WssItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-User License Agreement (EULA).
        /// </summary>
        internal static string HelpTopic_eula {
            get {
                return ResourceManager.GetString("HelpTopic_eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Settings.
        /// </summary>
        internal static string HelpTopic_farm_site_config {
            get {
                return ResourceManager.GetString("HelpTopic_farm_site_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using LookupZen.
        /// </summary>
        internal static string HelpTopic_intro {
            get {
                return ResourceManager.GetString("HelpTopic_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        internal static string HelpTopic_release_notes {
            get {
                return ResourceManager.GetString("HelpTopic_release_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Installation.
        /// </summary>
        internal static string HelpTopic_setup {
            get {
                return ResourceManager.GetString("HelpTopic_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo the description.
        /// </summary>
        internal static string WssField_roxority_LookupZenField {
            get {
                return ResourceManager.GetString("WssField_roxority_LookupZenField", resourceCulture);
            }
        }
    }
}
