//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roxority_SetupZen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("roxority_SetupZen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string AbortButton {
            get {
                return ResourceManager.GetString("AbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating farm features..
        /// </summary>
        internal static string ActivateFarmFeatures {
            get {
                return ResourceManager.GetString("ActivateFarmFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating features on {0} site collection(s)..
        /// </summary>
        internal static string ActivateSiteFeatures {
            get {
                return ResourceManager.GetString("ActivateSiteFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding solution to the SharePoint solution store..
        /// </summary>
        internal static string AddSolution {
            get {
                return ResourceManager.GetString("AddSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled. Rolling back all operations..
        /// </summary>
        internal static string CancelRollback {
            get {
                return ResourceManager.GetString("CancelRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Central Administration — always KEEP deployed to this target!).
        /// </summary>
        internal static string CentralAdmin {
            get {
                return ResourceManager.GetString("CentralAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if {SolutionTitle} can be installed from here....
        /// </summary>
        internal static string Check2 {
            get {
                return ResourceManager.GetString("Check2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have permission to install and deploy SharePoint solutions?.
        /// </summary>
        internal static string CheckAdmin {
            get {
                return ResourceManager.GetString("CheckAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to install and deploy SharePoint solutions!.
        /// </summary>
        internal static string CheckAdminNo {
            get {
                return ResourceManager.GetString("CheckAdminNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have permission to install and deploy SharePoint solutions..
        /// </summary>
        internal static string CheckAdminYes {
            get {
                return ResourceManager.GetString("CheckAdminYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the above errors before installing {SolutionTitle}..
        /// </summary>
        internal static string CheckAllNo {
            get {
                return ResourceManager.GetString("CheckAllNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All checks succeeded. Please click &apos;Next&apos; to proceed with the installation..
        /// </summary>
        internal static string CheckAllYes {
            get {
                return ResourceManager.GetString("CheckAllYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the solution package exist?.
        /// </summary>
        internal static string CheckFile {
            get {
                return ResourceManager.GetString("CheckFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution package does not exist..
        /// </summary>
        internal static string CheckFileNo {
            get {
                return ResourceManager.GetString("CheckFileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution package exists..
        /// </summary>
        internal static string CheckFileYes {
            get {
                return ResourceManager.GetString("CheckFileYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Java Runtime Environment {0} installed?.
        /// </summary>
        internal static string CheckJava {
            get {
                return ResourceManager.GetString("CheckJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Runtime Environment {0} or higher is not installed..
        /// </summary>
        internal static string CheckJavaNo {
            get {
                return ResourceManager.GetString("CheckJavaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Runtime Environment {0} or higher is installed..
        /// </summary>
        internal static string CheckJavaYes {
            get {
                return ResourceManager.GetString("CheckJavaYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is SharePoint Server / MOSS installed?.
        /// </summary>
        internal static string CheckMoss {
            get {
                return ResourceManager.GetString("CheckMoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Server / MOSS is not installed..
        /// </summary>
        internal static string CheckMossNo {
            get {
                return ResourceManager.GetString("CheckMossNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This deployment wizard tried to detect the type of your SharePoint installation, but this detection can be mistaken at times. For this software package to be installed correctly, your truthful confirmation or denial of the following is CRUCIAL:
        ///
        ///Is this a {0} environment? Click YES.
        ///Is this a {2} environment? Click NO.
        ///
        ///The deployment wizard thinks: this SharePoint farm is a {0} environment ({1} {2} environment) --- is this CORRECT?.
        /// </summary>
        internal static string CheckMossPrompt {
            get {
                return ResourceManager.GetString("CheckMossPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not just a.
        /// </summary>
        internal static string CheckMossPromptIfMoss {
            get {
                return ResourceManager.GetString("CheckMossPromptIfMoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but not a.
        /// </summary>
        internal static string CheckMossPromptIfWss {
            get {
                return ResourceManager.GetString("CheckMossPromptIfWss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Server 2010 or MOSS 2007.
        /// </summary>
        internal static string CheckMossPromptMoss {
            get {
                return ResourceManager.GetString("CheckMossPromptMoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Foundation 2010, WSS 3.0 or MS Search Server.
        /// </summary>
        internal static string CheckMossPromptWss {
            get {
                return ResourceManager.GetString("CheckMossPromptWss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Foundation / Search Server (WSS) or SharePoint Server (MOSS)?.
        /// </summary>
        internal static string CheckMossTitle {
            get {
                return ResourceManager.GetString("CheckMossTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Server / MOSS is installed..
        /// </summary>
        internal static string CheckMossYes {
            get {
                return ResourceManager.GetString("CheckMossYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Windows SharePoint Services Administration service running?.
        /// </summary>
        internal static string CheckService {
            get {
                return ResourceManager.GetString("CheckService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Administration service is not running..
        /// </summary>
        internal static string CheckServiceNo {
            get {
                return ResourceManager.GetString("CheckServiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Administration service is running..
        /// </summary>
        internal static string CheckServiceYes {
            get {
                return ResourceManager.GetString("CheckServiceYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting {SolutionTitle}....
        /// </summary>
        internal static string CheckSolution {
            get {
                return ResourceManager.GetString("CheckSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to detect {SolutionTitle}..
        /// </summary>
        internal static string CheckSolutionNo {
            get {
                return ResourceManager.GetString("CheckSolutionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} is not installed..
        /// </summary>
        internal static string CheckSolutionYes {
            get {
                return ResourceManager.GetString("CheckSolutionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Windows SharePoint Services Timer service running?.
        /// </summary>
        internal static string CheckTimer {
            get {
                return ResourceManager.GetString("CheckTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Timer service is not running..
        /// </summary>
        internal static string CheckTimerNo {
            get {
                return ResourceManager.GetString("CheckTimerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Windows SharePoint Services Timer service is running..
        /// </summary>
        internal static string CheckTimerYes {
            get {
                return ResourceManager.GetString("CheckTimerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is SharePoint Foundation / WSS installed?.
        /// </summary>
        internal static string CheckWss {
            get {
                return ResourceManager.GetString("CheckWss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Foundation / WSS is not installed..
        /// </summary>
        internal static string CheckWssNo {
            get {
                return ResourceManager.GetString("CheckWssNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Foundation / WSS is installed..
        /// </summary>
        internal static string CheckWssYes {
            get {
                return ResourceManager.GetString("CheckWssYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Studio for site collection {0}.
        /// </summary>
        internal static string ConfigButton {
            get {
                return ResourceManager.GetString("ConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error: solution ID is invalid..
        /// </summary>
        internal static string ConfigErrorInvalidSolutionID {
            get {
                return ResourceManager.GetString("ConfigErrorInvalidSolutionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error: no solution package was specified..
        /// </summary>
        internal static string ConfigErrorNoSolution {
            get {
                return ResourceManager.GetString("ConfigErrorNoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error: solution ID is missing..
        /// </summary>
        internal static string ConfigErrorNoSolutionID {
            get {
                return ResourceManager.GetString("ConfigErrorNoSolutionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating farm features..
        /// </summary>
        internal static string DeactivateFarmFeatures {
            get {
                return ResourceManager.GetString("DeactivateFarmFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating site collection features..
        /// </summary>
        internal static string DeactivateSiteFeatures {
            get {
                return ResourceManager.GetString("DeactivateSiteFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a job for deploying the solution to all applicable web applications..
        /// </summary>
        internal static string DeploySolution {
            get {
                return ResourceManager.GetString("DeploySolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another deployment job for this solution is currently running..
        /// </summary>
        internal static string DoubleDeployment {
            get {
                return ResourceManager.GetString("DoubleDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** ERROR *****.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. Could not read the Windows Registry key &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorRegistryAccess {
            get {
                return ResourceManager.GetString("ErrorRegistryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-User License Agreement (EULA).
        /// </summary>
        internal static string Eula {
            get {
                return ResourceManager.GetString("Eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the following license agreement carefully:.
        /// </summary>
        internal static string Eula2 {
            get {
                return ResourceManager.GetString("Eula2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Cannot access root web site: access denied&gt;.
        /// </summary>
        internal static string FailedRootWebTitle {
            get {
                return ResourceManager.GetString("FailedRootWebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Deployment Targets.
        /// </summary>
        internal static string FarmDeploymentTargets {
            get {
                return ResourceManager.GetString("FarmDeploymentTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more web applications.
        /// </summary>
        internal static string FarmDeploymentTargets2 {
            get {
                return ResourceManager.GetString("FarmDeploymentTargets2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** FEATURE ACTIVATION *****.
        /// </summary>
        internal static string FeatureActivation {
            get {
                return ResourceManager.GetString("FeatureActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** FEATURE DEACTIVATION *****.
        /// </summary>
        internal static string FeatureDeactivation {
            get {
                return ResourceManager.GetString("FeatureDeactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors detected. Rolling back all operations..
        /// </summary>
        internal static string FinFailAll {
            get {
                return ResourceManager.GetString("FinFailAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Failed.
        /// </summary>
        internal static string FinFailInstall {
            get {
                return ResourceManager.GetString("FinFailInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Failed.
        /// </summary>
        internal static string FinFailRepair {
            get {
                return ResourceManager.GetString("FinFailRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback completed with {0} error(s). Please see log file for details..
        /// </summary>
        internal static string FinFailRollback {
            get {
                return ResourceManager.GetString("FinFailRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Failed.
        /// </summary>
        internal static string FinFailUninstall {
            get {
                return ResourceManager.GetString("FinFailUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Failed.
        /// </summary>
        internal static string FinFailUpgrade {
            get {
                return ResourceManager.GetString("FinFailUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} was successfully installed..
        /// </summary>
        internal static string Finished2 {
            get {
                return ResourceManager.GetString("Finished2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All operations successfully completed..
        /// </summary>
        internal static string FinSuccAll {
            get {
                return ResourceManager.GetString("FinSuccAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Successfully Completed.
        /// </summary>
        internal static string FinSuccInstall {
            get {
                return ResourceManager.GetString("FinSuccInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Successfully Completed.
        /// </summary>
        internal static string FinSuccRepair {
            get {
                return ResourceManager.GetString("FinSuccRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback successfully completed..
        /// </summary>
        internal static string FinSuccRollback {
            get {
                return ResourceManager.GetString("FinSuccRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Successfully Completed.
        /// </summary>
        internal static string FinSuccUninstall {
            get {
                return ResourceManager.GetString("FinSuccUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Successfully Completed.
        /// </summary>
        internal static string FinSuccUpgrade {
            get {
                return ResourceManager.GetString("FinSuccUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint was unable to connect to the database..
        /// </summary>
        internal static string InstallException {
            get {
                return ResourceManager.GetString("InstallException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is being installed..
        /// </summary>
        internal static string Installing2 {
            get {
                return ResourceManager.GetString("Installing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may use files\zupjava{0}.exe to install Java manually yourself. Run files\zupjava{0}.exe /? for information about administrative or network installations. Please re-run this setup wizard once you have completed the Java installation successfully..
        /// </summary>
        internal static string JavaNoInstall {
            get {
                return ResourceManager.GetString("JavaNoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required minimum Java Runtime Environment version was not detected on this system and needs to be installed before proceeding with the installation. Would you like the setup wizard to install Java now?.
        /// </summary>
        internal static string JavaNope {
            get {
                return ResourceManager.GetString("JavaNope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning server farm for incompatible legacy Lists (may take a few minutes).
        /// </summary>
        internal static string Legacy {
            get {
                return ResourceManager.GetString("Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible legacy Lists found. You cannot proceed with deployment until these have been fully deleted (not just recycled). The LegacyMigration.exe tool guides you through this process and backs them up for later re-import --- run it NOW.
        ///(Note: if a previous ExportZen version is still installed, DO NOT uninstall it just yet; and when you later re-launch this wizard, pick Uninstall rather than the Update option!).
        /// </summary>
        internal static string LegacyFail {
            get {
                return ResourceManager.GetString("LegacyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK (no incompatible legacy Lists found) --- you can proceed with the installation.
        ///However, IF ExportZen 1.5 or earlier ever was (or still is) installed in this server farm, then (but only then) you SHOULD abort this wizard now, run the LegacyMigration.exe tool and follow its instructions. If not, it is safe to proceed now..
        /// </summary>
        internal static string LegacyOK {
            get {
                return ResourceManager.GetString("LegacyOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Number of Site Collections.
        /// </summary>
        internal static string ManySites {
            get {
                return ResourceManager.GetString("ManySites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} site collections within this web application.
        ///Showing a lot of site collections may take significant time.
        ///If you want to deploy to all site collections in this web application,
        ///you can simply check the web application checkbox without expanding it,
        ///however this will still take considerable time during the install process.
        ///Are you sure you want to show all {0} site collections for this web application?.
        /// </summary>
        internal static string ManySitesWarning {
            get {
                return ResourceManager.GetString("ManySitesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvParams.
        /// </summary>
        internal static string map_1f9fd01fdfd441bab3f06394a4616130 {
            get {
                return ResourceManager.GetString("map_1f9fd01fdfd441bab3f06394a4616130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormControls.
        /// </summary>
        internal static string map_306ab001d4f742bea88b52aed35d4e4b {
            get {
                return ResourceManager.GetString("map_306ab001d4f742bea88b52aed35d4e4b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncLock.
        /// </summary>
        internal static string map_776c627b79754891a0a0398fbdd8d3e9 {
            get {
                return ResourceManager.GetString("map_776c627b79754891a0a0398fbdd8d3e9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collation.
        /// </summary>
        internal static string map_89e8fd8bfe57477bb10a1f6adee43cff {
            get {
                return ResourceManager.GetString("map_89e8fd8bfe57477bb10a1f6adee43cff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafeVects.
        /// </summary>
        internal static string map_c2bdf2cea3ab4818b3dced592beec0ff {
            get {
                return ResourceManager.GetString("map_c2bdf2cea3ab4818b3dced592beec0ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsageTrace.
        /// </summary>
        internal static string map_dce8c4692132425b9065151f090ea138 {
            get {
                return ResourceManager.GetString("map_dce8c4692132425b9065151f090ea138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SharePoint Timer Service is either not running, could not be re-started or its status could not be determined. If the service is in fact running just fine, then re-running this setup wizard with administrative privilegues (right-click in Windows Explorer and &apos;Run as Administrator&apos;) usually resolves this issue..
        /// </summary>
        internal static string NoTimerHint {
            get {
                return ResourceManager.GetString("NoTimerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade/repair not possible with the currently installed version. Perform a full uninstall first, then re-run this deployment wizard to install..
        /// </summary>
        internal static string NoUpgrade {
            get {
                return ResourceManager.GetString("NoUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 59, 93, 27, 196, 200, 27, 77, 111, 130, 178, 123, 169, 115, 17, 200, 112, 243, 238, 77, 30, 165, 254, 25, 173, 6, 105, 57, 51, 187, 86, 42, 204, 89, 12, 44, 42, 185, 176, 181, 157, 89, 21, 141, 120, 140, 192, 4, 66, 57, 91, 109, 220, 179, 14, 112, 210, 193, 56, 28, 13, 159, 117, 57, 105, 112, 129, 255, 19, 228, 204, 188, 173, 221, 131, 91, 59, 55, 147, 252, 116, 183, 93, 240, 202, 197, 48, 169, 214, 32, 97, 54, 39, 166, 99, 120, 188, 208, 242 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_1f9fd01fdfd441bab3f06394a4616130 {
            get {
                return ResourceManager.GetString("pid_1f9fd01fdfd441bab3f06394a4616130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 141, 83, 245, 77, 131, 72, 129, 28, 245, 74, 166, 33, 208, 26, 38, 91, 7, 121, 99, 83, 194, 119, 235, 187, 41, 53, 41, 8, 33, 31, 117, 54, 37, 226, 255, 85, 121, 160, 51, 25, 95, 119, 175, 126, 22, 148, 144, 242, 26, 55, 72, 211, 254, 176, 64, 179, 159, 245, 2, 5, 81, 182, 118, 229, 135, 126, 192, 0, 249, 190, 184, 139, 110, 225, 68, 95, 93, 40, 226, 23, 253, 129, 145, 179, 173, 247, 158, 149, 118, 107, 19, 32, 204, 181, 1, 112, 74, 57, 235,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_306ab001d4f742bea88b52aed35d4e4b {
            get {
                return ResourceManager.GetString("pid_306ab001d4f742bea88b52aed35d4e4b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 191, 110, 41, 34, 52, 162, 132, 114, 98, 89, 127, 99, 38, 32, 0, 75, 155, 165, 4, 215, 182, 237, 1, 70, 86, 242, 248, 67, 193, 185, 124, 162, 14, 91, 84, 52, 223, 228, 64, 235, 203, 153, 16, 252, 202, 159, 119, 225, 45, 154, 96, 202, 200, 198, 14, 65, 255, 205, 174, 233, 194, 127, 125, 236, 82, 96, 92, 128, 159, 147, 32, 57, 226, 124, 128, 20, 197, 229, 111, 156, 243, 191, 23, 35, 232, 6, 29, 0, 158, 254, 85, 36, 23, 253, 243, 195, 229, 119,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_776c627b79754891a0a0398fbdd8d3e9 {
            get {
                return ResourceManager.GetString("pid_776c627b79754891a0a0398fbdd8d3e9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 161, 233, 120, 128, 228, 82, 89, 25, 218, 58, 250, 238, 152, 227, 130, 105, 151, 42, 234, 134, 14, 34, 236, 101, 209, 237, 21, 126, 243, 214, 137, 124, 122, 166, 55, 171, 230, 73, 156, 5, 110, 57, 128, 61, 142, 82, 157, 171, 17, 168, 115, 123, 112, 182, 152, 210, 115, 66, 189, 78, 149, 105, 118, 201, 24, 145, 243, 65, 166, 80, 197, 144, 92, 118, 253, 221, 20, 88, 83, 224, 126, 113, 43, 45, 118, 24, 101, 236, 158, 192, 217, 222, 170, 222, 244, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_89e8fd8bfe57477bb10a1f6adee43cff {
            get {
                return ResourceManager.GetString("pid_89e8fd8bfe57477bb10a1f6adee43cff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 147, 34, 158, 161, 199, 128, 252, 101, 121, 8, 183, 244, 119, 203, 179, 68, 21, 127, 103, 77, 74, 174, 138, 120, 4, 49, 150, 85, 194, 22, 52, 18, 45, 232, 115, 117, 237, 241, 176, 126, 76, 6, 238, 101, 225, 230, 95, 128, 190, 164, 194, 96, 116, 126, 90, 228, 69, 1, 66, 158, 72, 183, 175, 23, 198, 73, 170, 176, 85, 183, 99, 177, 123, 91, 243, 141, 1, 144, 122, 40, 223, 69, 217, 43, 249, 203, 16, 47, 236, 133, 180, 217, 198, 207, 136, 26, 87, 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_c2bdf2cea3ab4818b3dced592beec0ff {
            get {
                return ResourceManager.GetString("pid_c2bdf2cea3ab4818b3dced592beec0ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 237, 85, 209, 49, 73, 6, 147, 117, 81, 68, 162, 15, 109, 26, 59, 67, 58, 197, 52, 244, 164, 186, 179, 155, 234, 21, 245, 9, 209, 109, 131, 225, 17, 75, 196, 68, 68, 131, 184, 74, 240, 105, 246, 241, 193, 64, 17, 214, 143, 28, 43, 219, 101, 9, 167, 182, 248, 18, 61, 212, 94, 98, 178, 60, 72, 240, 218, 212, 177, 48, 134, 151, 116, 119, 23, 57, 165, 35, 243, 188, 76, 32, 252, 71, 223, 111, 231, 205, 18, 12, 59, 219, 32, 48, 1, 212, 212, 235, 173 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_dce8c4692132425b9065151f090ea138 {
            get {
                return ResourceManager.GetString("pid_dce8c4692132425b9065151f090ea138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open {0}:.
        /// </summary>
        internal static string ProcessingError {
            get {
                return ResourceManager.GetString("ProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} Product Documentation (online).
        /// </summary>
        internal static string ProductDocumentation {
            get {
                return ResourceManager.GetString("ProductDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering version number..
        /// </summary>
        internal static string RegisterVersion {
            get {
                return ResourceManager.GetString("RegisterVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing solution from the SharePoint solution store..
        /// </summary>
        internal static string RemoveSolution {
            get {
                return ResourceManager.GetString("RemoveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string Removing {
            get {
                return ResourceManager.GetString("Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing....
        /// </summary>
        internal static string Repairing {
            get {
                return ResourceManager.GetString("Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair or Remove.
        /// </summary>
        internal static string RepairRemove {
            get {
                return ResourceManager.GetString("RepairRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the operation you wish to perform:.
        /// </summary>
        internal static string RepairRemove2 {
            get {
                return ResourceManager.GetString("RepairRemove2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a job for retracting the solution from all web applications..
        /// </summary>
        internal static string RetractSolution {
            get {
                return ResourceManager.GetString("RetractSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Shared Resource Provider — always KEEP deployed to this target!).
        /// </summary>
        internal static string SharedResourceProvider {
            get {
                return ResourceManager.GetString("SharedResourceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Targets.
        /// </summary>
        internal static string SiteDeploymentTargets {
            get {
                return ResourceManager.GetString("SiteDeploymentTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to deploy the solution?.
        /// </summary>
        internal static string SiteDeploymentTargets2 {
            get {
                return ResourceManager.GetString("SiteDeploymentTargets2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} site collection(s).
        /// </summary>
        internal static string Sites {
            get {
                return ResourceManager.GetString("Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** SOLUTION DEPLOYMENT *****.
        /// </summary>
        internal static string SolutionDeployment {
            get {
                return ResourceManager.GetString("SolutionDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the specified solution package &apos;{0}&apos;..
        /// </summary>
        internal static string SolutionFileNotFound {
            get {
                return ResourceManager.GetString("SolutionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} is already installed..
        /// </summary>
        internal static string SolutionInstalled {
            get {
                return ResourceManager.GetString("SolutionInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} is not installed..
        /// </summary>
        internal static string SolutionNotInstalled {
            get {
                return ResourceManager.GetString("SolutionNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** SOLUTION RETRACTION *****.
        /// </summary>
        internal static string SolutionRetraction {
            get {
                return ResourceManager.GetString("SolutionRetraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deployment wizard (WSP build version: {1}).
        /// </summary>
        internal static string SolutionTitle {
            get {
                return ResourceManager.GetString("SolutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***** SOLUTION UPGRADE *****.
        /// </summary>
        internal static string SolutionUpgrade {
            get {
                return ResourceManager.GetString("SolutionUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint was unable to connect to the database server..
        /// </summary>
        internal static string SpDbError {
            get {
                return ResourceManager.GetString("SpDbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SQL Server Database.
        /// </summary>
        internal static string Sql {
            get {
                return ResourceManager.GetString("Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software requires its own SQL Server database:.
        /// </summary>
        internal static string Sql2 {
            get {
                return ResourceManager.GetString("Sql2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup created the specified database successfully. Click &apos;Next&apos; to proceed..
        /// </summary>
        internal static string SqlCreated {
            get {
                return ResourceManager.GetString("SqlCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the {0} detected SQL Server instance(s) above; or to use another one, type its name..
        /// </summary>
        internal static string SqlInstances {
            get {
                return ResourceManager.GetString("SqlInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting existing SQL Server instances....
        /// </summary>
        internal static string SqlInstanceWait {
            get {
                return ResourceManager.GetString("SqlInstanceWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL Server instances could be detected. Maybe the SQL Server Browser service is not currently running. You may continue by manually entering the SQL Server instance, or retry the detection by clicking &apos;Previous&apos;, then &apos;Next&apos;..
        /// </summary>
        internal static string SqlNoInstances {
            get {
                return ResourceManager.GetString("SqlNoInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified database already exists and seems to have been created by this setup wizard originally. Are you sure you want to reuse this existing database in this installation?.
        /// </summary>
        internal static string SqlUseThis {
            get {
                return ResourceManager.GetString("SqlUseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: the operation timed out. Please try again..
        /// </summary>
        internal static string TimeoutError {
            get {
                return ResourceManager.GetString("TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistering version number..
        /// </summary>
        internal static string UnregisterVersion {
            get {
                return ResourceManager.GetString("UnregisterVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade or Remove.
        /// </summary>
        internal static string UpgradeRemove {
            get {
                return ResourceManager.GetString("UpgradeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a job for upgrading the solution on all applicable web applications..
        /// </summary>
        internal static string UpgradeSolution {
            get {
                return ResourceManager.GetString("UpgradeSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading....
        /// </summary>
        internal static string Upgrading {
            get {
                return ResourceManager.GetString("Upgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting (max. 15 minutes) for solution deployment job to complete..
        /// </summary>
        internal static string WaitDeploy {
            get {
                return ResourceManager.GetString("WaitDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is being installed..
        /// </summary>
        internal static string WaitInstalling {
            get {
                return ResourceManager.GetString("WaitInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is being removed..
        /// </summary>
        internal static string WaitRemoving {
            get {
                return ResourceManager.GetString("WaitRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is being repaired..
        /// </summary>
        internal static string WaitRepairing {
            get {
                return ResourceManager.GetString("WaitRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting (max. 15 minutes) for solution retraction job to complete..
        /// </summary>
        internal static string WaitRetract {
            get {
                return ResourceManager.GetString("WaitRetract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting (max. 15 minutes) for solution upgrade job to complete..
        /// </summary>
        internal static string WaitUpgrade {
            get {
                return ResourceManager.GetString("WaitUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {SolutionTitle} is being upgraded..
        /// </summary>
        internal static string WaitUpgrading {
            get {
                return ResourceManager.GetString("WaitUpgrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SolutionTitle} setup wizard.
        /// </summary>
        internal static string Welcome2 {
            get {
                return ResourceManager.GetString("Welcome2", resourceCulture);
            }
        }
    }
}
