//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roxUp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("roxUp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark entire &apos;{0}&apos; folder contents (files and sub-folders) for upload into &apos;{1}/{2}&apos;.
        /// </summary>
        internal static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload folders including files and sub-folders:.
        /// </summary>
        internal static string AddFolderGroup {
            get {
                return ResourceManager.GetString("AddFolderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could not be logged in successfully with the specified user name and password. Maybe just a typo -- please try again..
        /// </summary>
        internal static string AuthError_PasswordNotMatch {
            get {
                return ResourceManager.GetString("AuthError_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Bool_False {
            get {
                return ResourceManager.GetString("Bool_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Bool_True {
            get {
                return ResourceManager.GetString("Bool_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After cancellation, you can continue by clicking &apos;Upload Files&apos; again.
        ///Are you sure you want to cancel your upload?.
        /// </summary>
        internal static string CancelPrompt {
            get {
                return ResourceManager.GetString("CancelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display local folders if....
        /// </summary>
        internal static string Cat_BrowseDirs {
            get {
                return ResourceManager.GetString("Cat_BrowseDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display local files if....
        /// </summary>
        internal static string Cat_BrowseFiles {
            get {
                return ResourceManager.GetString("Cat_BrowseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (General).
        /// </summary>
        internal static string Cat_Misc {
            get {
                return ResourceManager.GetString("Cat_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Upload).
        /// </summary>
        internal static string Cat_Upload {
            get {
                return ResourceManager.GetString("Cat_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include sub-folders in folder bulk uploads if....
        /// </summary>
        internal static string Cat_ZipDirs {
            get {
                return ResourceManager.GetString("Cat_ZipDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include files in folder bulk uploads if....
        /// </summary>
        internal static string Cat_ZipFiles {
            get {
                return ResourceManager.GetString("Cat_ZipFiles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CHECKIN {
            get {
                object obj = ResourceManager.GetObject("CHECKIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CHECKOUT {
            get {
                object obj = ResourceManager.GetObject("CHECKOUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ {0} item/s ].
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move the selected files and folders to the Windows Recycle Bin?.
        /// </summary>
        internal static string DelPrompt {
            get {
                return ResourceManager.GetString("DelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Yes&apos; to show local folders with this characteristic in the local file browsing area (with &apos;Show Folders&apos; enabled) so they can be marked for upload, or &apos;No&apos; to exclude such sub-folders..
        /// </summary>
        internal static string Desc_BrowseDirs {
            get {
                return ResourceManager.GetString("Desc_BrowseDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Yes&apos; to show local files with this characteristic in the local file browsing area so they can be marked for upload, or &apos;No&apos; to exclude such files..
        /// </summary>
        internal static string Desc_BrowseFiles {
            get {
                return ResourceManager.GetString("Desc_BrowseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Yes&apos; to overwrite files that already exist in the SharePoint Document Library target folder under the given name, or &apos;No&apos; to not replace the existing file and produce a warning message instead..
        /// </summary>
        internal static string Desc_Overwrite {
            get {
                return ResourceManager.GetString("Desc_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture files are represented by an icon showing a preview of their content but this consumes additional system resources. Specify the maximum number of picture files that a folder can contain before preview icons are turned off for that folder. Use 0 to never show any preview icons. The default value is 96..
        /// </summary>
        internal static string Desc_PreviewThreshold {
            get {
                return ResourceManager.GetString("Desc_PreviewThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a character or text used to replace each unwanted character, ie. ~ &quot; # % &amp;&amp; * : &lt; &gt; ? / \ { | } in uploaded file or folder names. Clear this to simply remove the unwanted characters. The default value is the underscore (_)..
        /// </summary>
        internal static string Desc_Replace {
            get {
                return ResourceManager.GetString("Desc_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &apos;Yes&apos; to automatically select a file filter for the local file browsing area suitable for the target Document Library, or &apos;No&apos; to never automatically change your file filters..
        /// </summary>
        internal static string Desc_SuggestFiltersDocLibs {
            get {
                return ResourceManager.GetString("Desc_SuggestFiltersDocLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &apos;Yes&apos; to automatically select a file filter for the local file browsing area suitable for the target Document Library, or &apos;No&apos; to never automatically change your file filters..
        /// </summary>
        internal static string Desc_SuggestFiltersOtherLibs {
            get {
                return ResourceManager.GetString("Desc_SuggestFiltersOtherLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Yes&apos; to include local sub-folders with this characteristic in folder bulk uploads, or &apos;No&apos; to exclude such sub-folders..
        /// </summary>
        internal static string Desc_ZipDirs {
            get {
                return ResourceManager.GetString("Desc_ZipDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Yes&apos; to include local files with this characteristic in folder bulk uploads, or &apos;No&apos; to exclude such files..
        /// </summary>
        internal static string Desc_ZipFiles {
            get {
                return ResourceManager.GetString("Desc_ZipFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder hierarchies can be bulk-uploaded in a single ZIP-compressed transfer but this is not recommended for sets of large files. Specify the maximum total MB size of a folder before its upload will be split up into multiple smaller file transfers rather than transferring one large package. Use 0 to disable single ZIP-compressed transfers for bulk folder uploads. The default value is 40..
        /// </summary>
        internal static string Desc_ZipUploadThreshold {
            get {
                return ResourceManager.GetString("Desc_ZipUploadThreshold", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DoubleLeftArrowHS {
            get {
                object obj = ResourceManager.GetObject("DoubleLeftArrowHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoubleRightArrowHS {
            get {
                object obj = ResourceManager.GetObject("DoubleRightArrowHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap drive {
            get {
                object obj = ResourceManager.GetObject("drive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EDITGRID {
            get {
                object obj = ResourceManager.GetObject("EDITGRID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Empty ].
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value contained one or more invalid characters. Remove any occurrences of ~ &quot; # % &amp;&amp; * : &lt; &gt; ? / \ { | and }.
        /// </summary>
        internal static string Error_Replace {
            get {
                return ResourceManager.GetString("Error_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Attribute.
        /// </summary>
        internal static string FileAtt_Archive {
            get {
                return ResourceManager.GetString("FileAtt_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blocked by SharePoint).
        /// </summary>
        internal static string FileAtt_Blocked {
            get {
                return ResourceManager.GetString("FileAtt_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed Attribute.
        /// </summary>
        internal static string FileAtt_Compressed {
            get {
                return ResourceManager.GetString("FileAtt_Compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Empty).
        /// </summary>
        internal static string FileAtt_Empty {
            get {
                return ResourceManager.GetString("FileAtt_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Attribute.
        /// </summary>
        internal static string FileAtt_Encrypted {
            get {
                return ResourceManager.GetString("FileAtt_Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Access or Read Error).
        /// </summary>
        internal static string FileAtt_Error {
            get {
                return ResourceManager.GetString("FileAtt_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Attribute.
        /// </summary>
        internal static string FileAtt_Hidden {
            get {
                return ResourceManager.GetString("FileAtt_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-indexed Attribute.
        /// </summary>
        internal static string FileAtt_NotContentIndexed {
            get {
                return ResourceManager.GetString("FileAtt_NotContentIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Attribute.
        /// </summary>
        internal static string FileAtt_Offline {
            get {
                return ResourceManager.GetString("FileAtt_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only Attribute.
        /// </summary>
        internal static string FileAtt_ReadOnly {
            get {
                return ResourceManager.GetString("FileAtt_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reparse Point Attribute.
        /// </summary>
        internal static string FileAtt_ReparsePoint {
            get {
                return ResourceManager.GetString("FileAtt_ReparsePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparse Attribute.
        /// </summary>
        internal static string FileAtt_SparseFile {
            get {
                return ResourceManager.GetString("FileAtt_SparseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Attribute.
        /// </summary>
        internal static string FileAtt_System {
            get {
                return ResourceManager.GetString("FileAtt_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Attribute.
        /// </summary>
        internal static string FileAtt_Temporary {
            get {
                return ResourceManager.GetString("FileAtt_Temporary", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Filter2HS {
            get {
                object obj = ResourceManager.GetObject("Filter2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Folder).
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FOLDER1 {
            get {
                object obj = ResourceManager.GetObject("FOLDER1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory with files to be uploaded:.
        /// </summary>
        internal static string FolderDialog {
            get {
                return ResourceManager.GetString("FolderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; in &apos;{1}&apos;.
        /// </summary>
        internal static string FriendlyFolderName {
            get {
                return ResourceManager.GetString("FriendlyFolderName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not shown:.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folder(s).
        /// </summary>
        internal static string HiddenDirs {
            get {
                return ResourceManager.GetString("HiddenDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders are currently hidden (click here to show folders).
        /// </summary>
        internal static string HiddenDirsNoFolders {
            get {
                return ResourceManager.GetString("HiddenDirsNoFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) and {1} folder(s) not shown due to current settings.
        /// </summary>
        internal static string HiddenDirsSettings {
            get {
                return ResourceManager.GetString("HiddenDirsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s).
        /// </summary>
        internal static string HiddenFiles {
            get {
                return ResourceManager.GetString("HiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) not shown due to active file filters.
        /// </summary>
        internal static string HiddenFilesFilters {
            get {
                return ResourceManager.GetString("HiddenFilesFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadZen HINT: you can enable automatic check in / check out in the &apos;Upload Files&apos; drop-down menu..
        /// </summary>
        internal static string HintCheckInOut {
            get {
                return ResourceManager.GetString("HintCheckInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadZen HINT: you can check &apos;Overwrite existing files&apos; on the &apos;Settings&apos; tab under &apos;(Upload)&apos;..
        /// </summary>
        internal static string HintExists {
            get {
                return ResourceManager.GetString("HintExists", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ICDOCX {
            get {
                object obj = ResourceManager.GetObject("ICDOCX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICJPEG {
            get {
                object obj = ResourceManager.GetObject("ICJPEG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICMASTER {
            get {
                object obj = ResourceManager.GetObject("ICMASTER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICSTP {
            get {
                object obj = ResourceManager.GetObject("ICSTP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading.
        /// </summary>
        internal static string MiniStatus_Load {
            get {
                return ResourceManager.GetString("MiniStatus_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending.
        /// </summary>
        internal static string MiniStatus_Up {
            get {
                return ResourceManager.GetString("MiniStatus_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zipping.
        /// </summary>
        internal static string MiniStatus_Zip {
            get {
                return ResourceManager.GetString("MiniStatus_Zip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MoveFolderHS {
            get {
                object obj = ResourceManager.GetObject("MoveFolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoveToFolderHS {
            get {
                object obj = ResourceManager.GetObject("MoveToFolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavBack {
            get {
                object obj = ResourceManager.GetObject("NavBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openfolderHS {
            get {
                object obj = ResourceManager.GetObject("openfolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Filter ({0}).
        /// </summary>
        internal static string OtherFilter {
            get {
                return ResourceManager.GetString("OtherFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PERUSR {
            get {
                object obj = ResourceManager.GetObject("PERUSR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PropertiesHS {
            get {
                object obj = ResourceManager.GetObject("PropertiesHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PublishPlanHS {
            get {
                object obj = ResourceManager.GetObject("PublishPlanHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap REFRESH {
            get {
                object obj = ResourceManager.GetObject("REFRESH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightsRestrictedHS {
            get {
                object obj = ResourceManager.GetObject("RightsRestrictedHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Root].
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServiceNotInstalled {
            get {
                object obj = ResourceManager.GetObject("ServiceNotInstalled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ {0} ].
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not fully uploaded.
        /// </summary>
        internal static string Status_None {
            get {
                return ResourceManager.GetString("Status_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uploaded.
        /// </summary>
        internal static string Status_Success {
            get {
                return ResourceManager.GetString("Status_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string Status_Uploading {
            get {
                return ResourceManager.GetString("Status_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0}, Selected: {1}.
        /// </summary>
        internal static string StatusInfo {
            get {
                return ResourceManager.GetString("StatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload: {0}% ({5} / {2}), {3} done, {4} failed, {1} pending.
        /// </summary>
        internal static string StatusProgress {
            get {
                return ResourceManager.GetString("StatusProgress", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sts_list_genericlist16 {
            get {
                object obj = ResourceManager.GetObject("sts_list_genericlist16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STSICON {
            get {
                object obj = ResourceManager.GetObject("STSICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing files.
        /// </summary>
        internal static string Title_Overwrite {
            get {
                return ResourceManager.GetString("Title_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum picture file preview icons per folder.
        /// </summary>
        internal static string Title_PreviewThreshold {
            get {
                return ResourceManager.GetString("Title_PreviewThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement character.
        /// </summary>
        internal static string Title_Replace {
            get {
                return ResourceManager.GetString("Title_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the Documents file filter when targeting a Document Library.
        /// </summary>
        internal static string Title_SuggestFiltersDocLibs {
            get {
                return ResourceManager.GetString("Title_SuggestFiltersDocLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the appropriate file filter when targeting a Picture Library, Gallery or Catalog.
        /// </summary>
        internal static string Title_SuggestFiltersOtherLibs {
            get {
                return ResourceManager.GetString("Title_SuggestFiltersOtherLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum folder size (MB) for folder bulk uploads via single ZIP-compressed transfer.
        /// </summary>
        internal static string Title_ZipUploadThreshold {
            get {
                return ResourceManager.GetString("Title_ZipUploadThreshold", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UPFOLDER {
            get {
                object obj = ResourceManager.GetObject("UPFOLDER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WEBPART {
            get {
                object obj = ResourceManager.GetObject("WEBPART", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body
        ///		{
        ///			background-color: Window;
        ///			color: WindowText;
        ///			font-family: &quot;Helvetica Neue&quot; , Arial, Helvetica, Sans-Serif;
        ///			font-size: 11px;
        ///			line-height: 1.8em;
        ///		}
        ///		h3
        ///		{
        ///			border-bottom: #c0c0a0 1px dotted;
        ///			margin: 0px !important;
        ///			padding: 0px !important;
        ///			font-size: 20px;
        ///			letter-spacing: -1px;
        ///			color: #909070;
        ///			font-weight: normal;
        ///		}
        ///		img
        ///		{
        ///			margin: 0px 3px 0px 3px;
        ///			width: 16px !important;
        ///			height: 16px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /help/welcome.html.
        /// </summary>
        internal static string WelcomeLink {
            get {
                return ResourceManager.GetString("WelcomeLink", resourceCulture);
            }
        }
    }
}
