//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamlTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CamlTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Where&gt;
        ///	&lt;Or&gt;
        ///		&lt;Eq&gt;
        ///			&lt;FieldRef Name=&quot;LinkTitle&quot; /&gt;
        ///			&lt;Value Type=&quot;Computed&quot;&gt;2&lt;/Value&gt;
        ///		&lt;/Eq&gt;
        ///		&lt;Or&gt;
        ///			&lt;Eq&gt;
        ///				&lt;FieldRef Name=&quot;PercentComplete&quot; /&gt;
        ///				&lt;Value Type=&quot;Number&quot;&gt;not&lt;/Value&gt;
        ///			&lt;/Eq&gt;
        ///			&lt;Or&gt;
        ///				&lt;Eq&gt;
        ///					&lt;FieldRef Name=&quot;AssignedTo&quot; /&gt;
        ///					&lt;Value Type=&quot;User&quot;&gt;not&lt;/Value&gt;
        ///				&lt;/Eq&gt;
        ///				&lt;Or&gt;
        ///					&lt;Eq&gt;
        ///						&lt;FieldRef Name=&quot;DueDate&quot; /&gt;
        ///						&lt;Value Type=&quot;DateTime&quot; IncludeTimeValue=&quot;FALSE&quot;&gt;0001-01-01T00:00:00Z&lt;/Value&gt;
        ///					&lt;/Eq&gt;
        ///					&lt;Or&gt;
        ///						&lt;Eq&gt;
        ///							&lt;FieldRef Name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
    }
}
