//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roxority_Deploy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("roxority_Deploy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELLED..
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DON&apos;T quit or kill this process before it finishes!.
        /// </summary>
        internal static string DontQuit {
            get {
                return ResourceManager.GetString("DontQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Working on it...&quot;.
        /// </summary>
        internal static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to EXIT the installer..
        /// </summary>
        internal static string ExitPrompt {
            get {
                return ResourceManager.GetString("ExitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnvParams.
        /// </summary>
        internal static string map_1f9fd01fdfd441bab3f06394a4616130 {
            get {
                return ResourceManager.GetString("map_1f9fd01fdfd441bab3f06394a4616130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormControls.
        /// </summary>
        internal static string map_306ab001d4f742bea88b52aed35d4e4b {
            get {
                return ResourceManager.GetString("map_306ab001d4f742bea88b52aed35d4e4b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncLock.
        /// </summary>
        internal static string map_776c627b79754891a0a0398fbdd8d3e9 {
            get {
                return ResourceManager.GetString("map_776c627b79754891a0a0398fbdd8d3e9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collation.
        /// </summary>
        internal static string map_89e8fd8bfe57477bb10a1f6adee43cff {
            get {
                return ResourceManager.GetString("map_89e8fd8bfe57477bb10a1f6adee43cff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SafeVects.
        /// </summary>
        internal static string map_c2bdf2cea3ab4818b3dced592beec0ff {
            get {
                return ResourceManager.GetString("map_c2bdf2cea3ab4818b3dced592beec0ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsageTrace.
        /// </summary>
        internal static string map_dce8c4692132425b9065151f090ea138 {
            get {
                return ResourceManager.GetString("map_dce8c4692132425b9065151f090ea138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 59, 93, 27, 196, 200, 27, 77, 111, 130, 178, 123, 169, 115, 17, 200, 112, 243, 238, 77, 30, 165, 254, 25, 173, 6, 105, 57, 51, 187, 86, 42, 204, 89, 12, 44, 42, 185, 176, 181, 157, 89, 21, 141, 120, 140, 192, 4, 66, 57, 91, 109, 220, 179, 14, 112, 210, 193, 56, 28, 13, 159, 117, 57, 105, 112, 129, 255, 19, 228, 204, 188, 173, 221, 131, 91, 59, 55, 147, 252, 116, 183, 93, 240, 202, 197, 48, 169, 214, 32, 97, 54, 39, 166, 99, 120, 188, 208, 242 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_1f9fd01fdfd441bab3f06394a4616130 {
            get {
                return ResourceManager.GetString("pid_1f9fd01fdfd441bab3f06394a4616130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 141, 83, 245, 77, 131, 72, 129, 28, 245, 74, 166, 33, 208, 26, 38, 91, 7, 121, 99, 83, 194, 119, 235, 187, 41, 53, 41, 8, 33, 31, 117, 54, 37, 226, 255, 85, 121, 160, 51, 25, 95, 119, 175, 126, 22, 148, 144, 242, 26, 55, 72, 211, 254, 176, 64, 179, 159, 245, 2, 5, 81, 182, 118, 229, 135, 126, 192, 0, 249, 190, 184, 139, 110, 225, 68, 95, 93, 40, 226, 23, 253, 129, 145, 179, 173, 247, 158, 149, 118, 107, 19, 32, 204, 181, 1, 112, 74, 57, 235,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_306ab001d4f742bea88b52aed35d4e4b {
            get {
                return ResourceManager.GetString("pid_306ab001d4f742bea88b52aed35d4e4b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 191, 110, 41, 34, 52, 162, 132, 114, 98, 89, 127, 99, 38, 32, 0, 75, 155, 165, 4, 215, 182, 237, 1, 70, 86, 242, 248, 67, 193, 185, 124, 162, 14, 91, 84, 52, 223, 228, 64, 235, 203, 153, 16, 252, 202, 159, 119, 225, 45, 154, 96, 202, 200, 198, 14, 65, 255, 205, 174, 233, 194, 127, 125, 236, 82, 96, 92, 128, 159, 147, 32, 57, 226, 124, 128, 20, 197, 229, 111, 156, 243, 191, 23, 35, 232, 6, 29, 0, 158, 254, 85, 36, 23, 253, 243, 195, 229, 119,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_776c627b79754891a0a0398fbdd8d3e9 {
            get {
                return ResourceManager.GetString("pid_776c627b79754891a0a0398fbdd8d3e9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 161, 233, 120, 128, 228, 82, 89, 25, 218, 58, 250, 238, 152, 227, 130, 105, 151, 42, 234, 134, 14, 34, 236, 101, 209, 237, 21, 126, 243, 214, 137, 124, 122, 166, 55, 171, 230, 73, 156, 5, 110, 57, 128, 61, 142, 82, 157, 171, 17, 168, 115, 123, 112, 182, 152, 210, 115, 66, 189, 78, 149, 105, 118, 201, 24, 145, 243, 65, 166, 80, 197, 144, 92, 118, 253, 221, 20, 88, 83, 224, 126, 113, 43, 45, 118, 24, 101, 236, 158, 192, 217, 222, 170, 222, 244, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_89e8fd8bfe57477bb10a1f6adee43cff {
            get {
                return ResourceManager.GetString("pid_89e8fd8bfe57477bb10a1f6adee43cff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 147, 34, 158, 161, 199, 128, 252, 101, 121, 8, 183, 244, 119, 203, 179, 68, 21, 127, 103, 77, 74, 174, 138, 120, 4, 49, 150, 85, 194, 22, 52, 18, 45, 232, 115, 117, 237, 241, 176, 126, 76, 6, 238, 101, 225, 230, 95, 128, 190, 164, 194, 96, 116, 126, 90, 228, 69, 1, 66, 158, 72, 183, 175, 23, 198, 73, 170, 176, 85, 183, 99, 177, 123, 91, 243, 141, 1, 144, 122, 40, 223, 69, 217, 43, 249, 203, 16, 47, 236, 133, 180, 217, 198, 207, 136, 26, 87, 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_c2bdf2cea3ab4818b3dced592beec0ff {
            get {
                return ResourceManager.GetString("pid_c2bdf2cea3ab4818b3dced592beec0ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 237, 85, 209, 49, 73, 6, 147, 117, 81, 68, 162, 15, 109, 26, 59, 67, 58, 197, 52, 244, 164, 186, 179, 155, 234, 21, 245, 9, 209, 109, 131, 225, 17, 75, 196, 68, 68, 131, 184, 74, 240, 105, 246, 241, 193, 64, 17, 214, 143, 28, 43, 219, 101, 9, 167, 182, 248, 18, 61, 212, 94, 98, 178, 60, 72, 240, 218, 212, 177, 48, 134, 151, 116, 119, 23, 57, 165, 35, 243, 188, 76, 32, 252, 71, 223, 111, 231, 205, 18, 12, 59, 219, 32, 48, 1, 212, 212, 235, 173 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pid_dce8c4692132425b9065151f090ea138 {
            get {
                return ResourceManager.GetString("pid_dce8c4692132425b9065151f090ea138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Loading setup configuration....
        /// </summary>
        internal static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution deployment configuration file not found or invalid..
        /// </summary>
        internal static string Step1Fail {
            get {
                return ResourceManager.GetString("Step1Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Connecting to local SharePoint server farm....
        /// </summary>
        internal static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access the local SharePoint server farm. Is SharePoint installed on this machine?.
        /// </summary>
        internal static string Step2Fail {
            get {
                return ResourceManager.GetString("Step2Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Checking server farm solution package deployment state....
        /// </summary>
        internal static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting solution package from SharePoint server farm....
        /// </summary>
        internal static string Step3Delete {
            get {
                return ResourceManager.GetString("Step3Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retracting solution package from SharePoint Web Applications:.
        /// </summary>
        internal static string Step3Retract {
            get {
                return ResourceManager.GetString("Step3Retract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is no longer installed in this SharePoint server farm..
        /// </summary>
        internal static string Step3Uninstalled {
            get {
                return ResourceManager.GetString("Step3Uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Adding solution package to SharePoint server farm....
        /// </summary>
        internal static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying solution package to SharePoint Web Applications....
        /// </summary>
        internal static string Step4Deploy {
            get {
                return ResourceManager.GetString("Step4Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install and deploy .
        /// </summary>
        internal static string Step4Prompt1 {
            get {
                return ResourceManager.GetString("Step4Prompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  NOW?.
        /// </summary>
        internal static string Step4Prompt2 {
            get {
                return ResourceManager.GetString("Step4Prompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any key to cancel, or ENTER to continue: .
        /// </summary>
        internal static string Step4Prompt3 {
            get {
                return ResourceManager.GetString("Step4Prompt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Package installer for SharePoint server farm.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a few minutes, please WAIT!.
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
